### ISSUE TITLE
maven build fails for aem-guides-wknd-spa-1.0.3-React 

### ISSUE THREAD

**Issue by gurudattshahane** [adobe/aem-guides-wknd-spa#38]
Hi Everyone,
I'm facing issue while building aem-guides-wknd-spa-1.0.3-React project with classic profile.
Please help me resolving this issue.
#### Steps to Reproduce
Run command: mvn clean install -PautoInstallSinglePackage -Pclassic

#### Platform and Version
Maven Version: 3.8.6
Java Version: openjdk version "1.8.0_402-402"
OS: Windows 11

#### Logs 
PS E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React> mvn clean install -PautoInstallSinglePackage -Pclassic
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] wknd-spa-react                                                     [pom]
[INFO] WKND SPA React - Core                                              [jar]
[INFO] wknd-spa-react.ui.frontend - UI Frontend                           [pom]
[INFO] WKND SPA React - Repository Structure Package          [content-package]
[INFO] WKND SPA React - UI apps                               [content-package]
[INFO] WKND SPA React - UI content                            [content-package]
[INFO] WKND SPA React - All                                   [content-package]
[INFO] WKND SPA React - Integration Tests                                 [jar]
[INFO] WKND SPA React - Dispatcher                                        [pom]
[INFO]
[INFO] ----------------< com.adobe.aem.guides:wknd-spa-react >-----------------
[INFO] Building wknd-spa-react 1.0.3-SNAPSHOT                             [1/9]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ wknd-spa-react ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ wknd-spa-react ---
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ wknd-spa-react ---
[INFO] Installing E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\pom.xml to C:\Users\Gurudatt\.m2\repository\com\adobe\aem\guides\wknd-spa-react\1.0.3-SNAPSHOT\wknd-spa-react-1.0.3-SNAPSHOT.pom
[INFO]
[INFO] --------------< com.adobe.aem.guides:wknd-spa-react.core >--------------
[INFO] Building WKND SPA React - Core 1.0.3-SNAPSHOT                      [2/9]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ wknd-spa-react.core ---
[INFO] Deleting E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\core\target
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ wknd-spa-react.core ---
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ wknd-spa-react.core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\core\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ wknd-spa-react.core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 14 source files to E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\core\target\classes
[INFO]
[INFO] --- bnd-maven-plugin:5.0.0:bnd-process (bnd-process) @ wknd-spa-react.core ---
[WARNING] E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\core\pom.xml [0:0]: No translation found for macro: componentGroupName
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ wknd-spa-react.core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\core\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ wknd-spa-react.core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\core\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ wknd-spa-react.core ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.adobe.aem.guides.wknd.spa.react.core.filters.LoggingFilterTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.359 s - in com.adobe.aem.guides.wknd.spa.react.core.filters.LoggingFilterTest
[INFO] Running com.adobe.aem.guides.wknd.spa.react.core.listeners.SimpleResourceListenerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in com.adobe.aem.guides.wknd.spa.react.core.listeners.SimpleResourceListenerTest
[INFO] Running com.adobe.aem.guides.wknd.spa.react.core.models.HelloWorldModelTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.033 s - in com.adobe.aem.guides.wknd.spa.react.core.models.HelloWorldModelTest
[INFO] Running com.adobe.aem.guides.wknd.spa.react.core.schedulers.SimpleScheduledTaskTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 s - in com.adobe.aem.guides.wknd.spa.react.core.schedulers.SimpleScheduledTaskTest
[INFO] Running com.adobe.aem.guides.wknd.spa.react.core.servlets.SimpleServletTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.026 s - in com.adobe.aem.guides.wknd.spa.react.core.servlets.SimpleServletTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:3.1.2:jar (default-jar) @ wknd-spa-react.core ---
[INFO] Building jar: E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\core\target\wknd-spa-react.core-1.0.3-SNAPSHOT.jar
[INFO]
[INFO] --- bnd-baseline-maven-plugin:5.0.0:baseline (baseline) @ wknd-spa-react.core ---
[INFO] Determining the baseline version for com.adobe.aem.guides:wknd-spa-react.core:jar:(,1.0.3-SNAPSHOT) using repositories [adobe (https://repo.adobe.com/nexus/content/groups/public/, default, releases+snapshots), adobe-public-releases (https://repo.adobe.com/nexus/content/groups/public, default, releases), adobe-aem-releases (https://downloads.experiencecloud.adobe.com/content/maven/public, default, releases), central (https://repo.maven.apache.org/maven2, default, releases)]
[INFO] The baseline version was found to be null
[WARNING] No previous version of com.adobe.aem.guides:wknd-spa-react.core:jar:1.0.3-SNAPSHOT could be found to baseline against
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ wknd-spa-react.core ---
[INFO] Installing E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\core\target\wknd-spa-react.core-1.0.3-SNAPSHOT.jar to C:\Users\Gurudatt\.m2\repository\com\adobe\aem\guides\wknd-spa-react.core\1.0.3-SNAPSHOT\wknd-spa-react.core-1.0.3-SNAPSHOT.jar
[INFO] Installing E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\core\pom.xml to C:\Users\Gurudatt\.m2\repository\com\adobe\aem\guides\wknd-spa-react.core\1.0.3-SNAPSHOT\wknd-spa-react.core-1.0.3-SNAPSHOT.pom
[INFO]
[INFO] ----------< com.adobe.aem.guides:wknd-spa-react.ui.frontend >-----------
[INFO] Building wknd-spa-react.ui.frontend - UI Frontend 1.0.3-SNAPSHOT   [3/9]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ wknd-spa-react.ui.frontend ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ wknd-spa-react.ui.frontend ---
[INFO]
[INFO] --- frontend-maven-plugin:1.7.6:install-node-and-npm (install node and npm) @ wknd-spa-react.ui.frontend ---
[INFO] Node v13.7.0 is already installed.
[INFO] NPM 6.13.0 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:1.7.6:npm (npm install) @ wknd-spa-react.ui.frontend ---
[INFO] Running 'npm install' in E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\ui.frontend
[WARNING] npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[WARNING] npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
[WARNING] npm WARN deprecated eslint-loader@3.0.3: This loader has been deprecated. Please use eslint-webpack-plugin
[WARNING] npm WARN deprecated html-webpack-plugin@4.0.0-beta.11: please switch to a stable version
[WARNING] npm WARN deprecated fsevents@2.1.2: "Please update to latest v2.3 or v2.2"
[WARNING] npm WARN deprecated @types/testing-library__dom@7.5.0: This is a stub types definition. testing-library__dom provides its own type definitions, so you do not need this installed.
[WARNING] npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[WARNING] npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
[WARNING] npm WARN deprecated har-validator@5.1.5: this library is no longer supported
[WARNING] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[WARNING] npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
[WARNING] npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
[WARNING] npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
[WARNING] npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
[WARNING] npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
[WARNING] npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
[WARNING] npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
[WARNING] npm WARN deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
[WARNING] npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
[WARNING] npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
[WARNING] npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
[WARNING] npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
[WARNING] npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
[WARNING] npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
[WARNING] npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
[WARNING] npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
[WARNING] npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
[WARNING] npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
[INFO]
[INFO] > @parcel/watcher@2.5.0 install E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\ui.frontend\node_modules\@parcel\watcher
[INFO] > node scripts/build-from-source.js
[INFO]
[INFO]
[INFO] > node-sass@4.14.1 install E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\ui.frontend\node_modules\node-sass
[INFO] > node scripts/install.js
[INFO]
[INFO] Cached binary found at C:\Users\Gurudatt\AppData\Roaming\npm-cache\node-sass\4.14.1\win32-x64-79_binding.node
[ERROR] (node:15888) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
[INFO]
[INFO] > core-js@2.6.12 postinstall E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\ui.frontend\node_modules\babel-runtime\node_modules\core-js
[INFO] > node -e "try{require('./postinstall')}catch(e){}"
[INFO]
[INFO] Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
[INFO]
[INFO] The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
[INFO] > https://opencollective.com/core-js
[INFO] > https://www.patreon.com/zloirock
[INFO]
[INFO] Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
[INFO]
[INFO]
[INFO] > core-js@3.39.0 postinstall E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\ui.frontend\node_modules\core-js
[INFO] > node -e "try{require('./postinstall')}catch(e){}"
[INFO]
[INFO] Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
[INFO]
[INFO] The project needs your help! Please consider supporting core-js:
[INFO] > https://opencollective.com/core-js
[INFO] > https://patreon.com/zloirock
[INFO] > https://boosty.to/zloirock
[INFO] > bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz
[INFO]
[INFO] I highly recommend reading this: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md
[INFO]
[INFO]
[INFO] > core-js-pure@3.39.0 postinstall E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\ui.frontend\node_modules\core-js-pure
[INFO] > node -e "try{require('./postinstall')}catch(e){}"
[INFO]
[INFO]
[INFO] > es5-ext@0.10.64 postinstall E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\ui.frontend\node_modules\es5-ext
[INFO] >  node -e "try{require('./_postinstall')}catch(e){}" || exit 0
[INFO]
[INFO]
[INFO] > node-sass@4.14.1 postinstall E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\ui.frontend\node_modules\node-sass
[INFO] > node scripts/build.js
[INFO]
[INFO] Binary found at E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\ui.frontend\node_modules\node-sass\vendor\win32-x64-79\binding.node
[INFO] Testing binary
[INFO] Binary is fine
[ERROR] npm notice created a lockfile as package-lock.json. You should commit this file.
[WARNING] npm WARN notsup Unsupported engine for @adobe/aem-spa-component-mapping@1.1.1: wanted: {"npm":">=6.14.4","node":">=12.16.2"} (current: {"node":"13.7.0","npm":"6.13.0"})
[WARNING] npm WARN notsup Not compatible with your version of node/npm: @adobe/aem-spa-component-mapping@1.1.1
[WARNING] npm WARN notsup Unsupported engine for @adobe/aem-react-editable-components@1.1.11: wanted: {"npm":"6.14.16","node":">=12.16.2"} (current: {"node":"13.7.0","npm":"6.13.0"})
[WARNING] npm WARN notsup Not compatible with your version of node/npm: @adobe/aem-react-editable-components@1.1.11
[WARNING] npm WARN notsup Unsupported engine for @adobe/aem-spa-page-model-manager@1.5.0: wanted: {"npm":">=6.14.15","node":">=12.16.2"} (current: {"node":"13.7.0","npm":"6.13.0"})
[WARNING] npm WARN notsup Not compatible with your version of node/npm: @adobe/aem-spa-page-model-manager@1.5.0
[WARNING] npm WARN notsup Unsupported engine for sass@1.81.0: wanted: {"node":">=14.0.0"} (current: {"node":"13.7.0","npm":"6.13.0"})
[WARNING] npm WARN notsup Not compatible with your version of node/npm: sass@1.81.0
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\react-scripts\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\jest-haste-map\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\chokidar\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN notsup Unsupported engine for chokidar@4.0.1: wanted: {"node":">= 14.16.0"} (current: {"node":"13.7.0","npm":"6.13.0"})
[WARNING] npm WARN notsup Not compatible with your version of node/npm: chokidar@4.0.1
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @parcel/watcher-darwin-x64@2.5.0 (node_modules\@parcel\watcher\node_modules\@parcel\watcher-darwin-x64):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @parcel/watcher-darwin-x64@2.5.0: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @parcel/watcher-win32-ia32@2.5.0 (node_modules\@parcel\watcher\node_modules\@parcel\watcher-win32-ia32):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @parcel/watcher-win32-ia32@2.5.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @parcel/watcher-darwin-arm64@2.5.0 (node_modules\@parcel\watcher\node_modules\@parcel\watcher-darwin-arm64):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @parcel/watcher-darwin-arm64@2.5.0: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @parcel/watcher-win32-arm64@2.5.0 (node_modules\@parcel\watcher\node_modules\@parcel\watcher-win32-arm64):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @parcel/watcher-win32-arm64@2.5.0: wanted {"os":"win32","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @parcel/watcher-linux-x64-glibc@2.5.0 (node_modules\@parcel\watcher\node_modules\@parcel\watcher-linux-x64-glibc):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @parcel/watcher-linux-x64-glibc@2.5.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @parcel/watcher-linux-x64-musl@2.5.0 (node_modules\@parcel\watcher\node_modules\@parcel\watcher-linux-x64-musl):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @parcel/watcher-linux-x64-musl@2.5.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @parcel/watcher-linux-arm64-glibc@2.5.0 (node_modules\@parcel\watcher\node_modules\@parcel\watcher-linux-arm64-glibc):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @parcel/watcher-linux-arm64-glibc@2.5.0: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @parcel/watcher-linux-arm64-musl@2.5.0 (node_modules\@parcel\watcher\node_modules\@parcel\watcher-linux-arm64-musl):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @parcel/watcher-linux-arm64-musl@2.5.0: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @parcel/watcher-linux-arm-musl@2.5.0 (node_modules\@parcel\watcher\node_modules\@parcel\watcher-linux-arm-musl):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @parcel/watcher-linux-arm-musl@2.5.0: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @parcel/watcher-android-arm64@2.5.0 (node_modules\@parcel\watcher\node_modules\@parcel\watcher-android-arm64):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @parcel/watcher-android-arm64@2.5.0: wanted {"os":"android","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @parcel/watcher-linux-arm-glibc@2.5.0 (node_modules\@parcel\watcher\node_modules\@parcel\watcher-linux-arm-glibc):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @parcel/watcher-linux-arm-glibc@2.5.0: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @parcel/watcher-freebsd-x64@2.5.0 (node_modules\@parcel\watcher\node_modules\@parcel\watcher-freebsd-x64):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @parcel/watcher-freebsd-x64@2.5.0: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"win32","arch":"x64"})
[WARNING] npm WARN notsup Unsupported engine for readdirp@4.0.2: wanted: {"node":">= 14.16.0"} (current: {"node":"13.7.0","npm":"6.13.0"})
[WARNING] npm WARN notsup Not compatible with your version of node/npm: readdirp@4.0.2
[WARNING] npm WARN notsup Unsupported engine for cheerio@1.0.0: wanted: {"node":">=18.17"} (current: {"node":"13.7.0","npm":"6.13.0"})
[WARNING] npm WARN notsup Not compatible with your version of node/npm: cheerio@1.0.0
[WARNING] npm WARN notsup Unsupported engine for undici@6.21.0: wanted: {"node":">=18.17"} (current: {"node":"13.7.0","npm":"6.13.0"})
[WARNING] npm WARN notsup Not compatible with your version of node/npm: undici@6.21.0
[WARNING] npm WARN notsup Unsupported engine for whatwg-mimetype@4.0.0: wanted: {"node":">=18"} (current: {"node":"13.7.0","npm":"6.13.0"})
[WARNING] npm WARN notsup Not compatible with your version of node/npm: whatwg-mimetype@4.0.0
[WARNING] npm WARN notsup Unsupported engine for whatwg-encoding@3.1.1: wanted: {"node":">=18"} (current: {"node":"13.7.0","npm":"6.13.0"})
[WARNING] npm WARN notsup Not compatible with your version of node/npm: whatwg-encoding@3.1.1
[WARNING] npm WARN @adobe/aem-react-editable-components@1.1.11 requires a peer of @adobe/aem-spa-page-model-manager@~1.4.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN sass-loader@8.0.2 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN @babel/plugin-transform-class-static-block@7.26.0 requires a peer of @babel/core@^7.12.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.25.9 requires a peer of @babel/core@^7.13.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN node-fetch@2.7.0 requires a peer of encoding@^0.1.0 but none is installed. You must install peer dependencies yourself.
[ERROR]
[INFO] added 2007 packages from 1315 contributors and audited 2024 packages in 100.178s
[INFO]
[INFO] 128 packages are looking for funding.
[INFO] Run "npm fund" to find out more.
[INFO]
[INFO] --- frontend-maven-plugin:1.7.6:npm (npm run test) @ wknd-spa-react.ui.frontend ---
[INFO] Running 'npm test' in E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\ui.frontend
[INFO]
[INFO] > wknd-spa-react@0.1.0 test E:\AEM\aem-author-java-8\Projects\aem-guides-wknd-spa-1.0.3-React\ui.frontend
[INFO] > react-scripts test
[INFO]
[ERROR] (node:4248) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
[ERROR] (node:7192) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
[ERROR] (node:13620) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
[ERROR] (node:1184) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
[ERROR] (node:9648) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
[ERROR] PASS src/utils/extract-model-id.test.js
[ERROR] PASS src/App.test.js
[ERROR] PASS src/components/Page/Page.test.js
[ERROR] PASS src/components/Text/Text.test.js
[ERROR] FAIL src/components/RouteHelper/RouteHelper.test.js
[ERROR]   â?? Test suite failed to run
[ERROR]
[ERROR]     Cannot find module 'node:stream' from 'index.js'
[ERROR]
[ERROR]     However, Jest was able to find:
[ERROR]         './Utils.js'
[ERROR]         './Utils.js.map'
[ERROR]
[ERROR]     You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].
[ERROR]
[ERROR]     See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
[ERROR]
[ERROR]     However, Jest was able to find:
[ERROR]         './ReactWrapper.js'
[ERROR]         './ReactWrapper.js.map'
[ERROR]
[ERROR]     You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].
[ERROR]
[ERROR]     See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
[ERROR]
[ERROR]       at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
[ERROR]       at Object.<anonymous> (node_modules/parse5-parser-stream/dist/cjs/index.js:4:23)
[ERROR]
[ERROR] Test Suites: 1 failed, 4 passed, 5 total
[ERROR] Tests:       10 passed, 10 total
[ERROR] Snapshots:   0 total
[ERROR] Time:        4.03s
[ERROR] Ran all test suites.
[ERROR] npm ERR! Test failed.  See above for more details.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for wknd-spa-react 1.0.3-SNAPSHOT:
[INFO]
[INFO] wknd-spa-react ..................................... SUCCESS [  0.260 s]
[INFO] WKND SPA React - Core .............................. SUCCESS [  5.672 s]
[INFO] wknd-spa-react.ui.frontend - UI Frontend ........... FAILURE [01:47 min]
[INFO] WKND SPA React - Repository Structure Package ...... SKIPPED
[INFO] WKND SPA React - UI apps ........................... SKIPPED
[INFO] WKND SPA React - UI content ........................ SKIPPED
[INFO] WKND SPA React - All ............................... SKIPPED
[INFO] WKND SPA React - Integration Tests ................. SKIPPED
[INFO] WKND SPA React - Dispatcher ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:54 min
[INFO] Finished at: 2024-11-23T13:23:30+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:npm (npm run test) on project wknd-spa-react.ui.frontend: Failed to run task: 'npm test' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :wknd-spa-react.ui.frontend

**Comment by ritikdhiman18** [comment]
Facing same issue tried debugging but didn't find anything yet.

**Comment by AswinCC23** [comment]
> Facing same issue tried debugging but didn't find anything yet.

@ritikdhiman18 @gurudattshahane  Got any solution?

**Comment by srinivasgv** [comment]
I am able to fix this by upgrading the versions for the below modules
`    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.8",`

and adding another module
`"cheerio": "1.0.0-rc.12"`

to the devDependencies. That helped in getting the build to pass successfully. Adding cheerio independently without updating enzyme versions or updating enzyme versions without without adding cheerio was not solving the issue.

I do not have much knowledge on UI development though. So there could be better solutions to fix this.
